Vyxal/Vyxal

Vyxal.py

Implicit input, unfortunately, doesn't work in Vyxal. I suggested a few fixes towards it.

Fix several bugs on implicit input

---

commands.py
docs/reference.txt

(This is untested, be sure to test it before you accept)
Also, the exact names for the functions is not determined yet.

PR for requested math functions

---

docs/reference.txt

* Added `k` instructions to reference
* Added more description towards the reference

Made reference a bit more comprehensive

---

.github/workflows/python-package.yml
Vyxal.py
tests/test_basic.py

To make sure stuff doesn't break when committing

Set up pytest workflow

---

templates/main.html

* Made the characters in the on-screen keyboard centered in their boxes
* Made the output box resize when pressing one of the submission generation buttons

Tweaked a couple things

---

commands.py

All of the print commands in `commands.py` had `printed = True` in them, which is unnecessary now that that statement is in `VY_print`.

Yeeted extraneous whatnots

---

templates/main.html

Added <kbd>Ctrl</kbd>+<kbd>Enter</kbd> key combination to run program in the online interpreter. Also made it so that the clear fields button resizes the fields as well.

look ma, no clicks!

---

templates/main.html

Made it so the textareas are ever so slightly larger so they don’t have a scrollbar.

Extra scrolling is for chumps

---

templates/index.html

Totally unnecessary but I was bored

Use template literals because why not

---

Vyxal.py

Also reorganized some of the flags.
Fixes #80

Added `Jo` flags to online interpreter

---

.github/workflows/run-tests.yml
.github/workflows/update-docs.yml

Also only use Python 3.8 for testing.

Only run tests in run-tests/python-package.yml

---

Vyxal.py
tests/test_basic.py

Return integers from is_prime

---

Vyxal.py

This is untested, and certainly incomplete,  which is why it's just a draft PR (hopefully that doesn't ping anyone).

Add some functions

---

Vyxal.py

Dictionary compression is now fully optimised. The algorithm works by iterating through the string and finding the longest compressible string at each point.

Improved dictionary compression

---

Vyxal.py

When you forget to actually return the result

Fix foldl_rows

---

dictionary.txt

I meant to revert this on the main repo

Reverted because I somehow missed that dictionary.py was a thing

---

Vyxal.py

It is still slightly slower than it would ideally be, so I will work on optimizing its speed later, but it is optimal in that it will always give the shortest possible output.

Optimize the string compression built-in

---

tests/test_lexer.py
tests/test_parser.py
tests/test_transpiler.py
vyxal/LazyList.py
vyxal/context.py
vyxal/elements.py
vyxal/encoding.py
vyxal/helpers.py
vyxal/lexer.py
vyxal/parse.py
vyxal/structure.py
vyxal/transpile.py
vyxal/vyxal.py

- Transpile If, While, and For.
- fixed `__repr__` of `Token` and `Structure` so that it can actually be used with `eval` to get tokens or structures back.
- Moved `transpile` to another file.
- Moved `Context` to its own file.

Transpile some structures

---

documents/protocols/code guide.md

paramemter -> parameter
This has to be the stupidest PR in all history

paramemter -> parameter

---

vyxal/Structure.py
vyxal/structure.py

Fresh beginnings

---

documents/knowledge/elements.yaml

All functions have been added. Requires proofreading.
Constants are still a TODO.

Finish adding all functions

---

.github/workflows/deploy.yaml
flask_app.py
funky_upgrade.sh
requirements_flask_app.txt

I used the word "funky" in a few places just to be non-generic in my descriptions of the system. It doesn't mean anything in particular.

Continuous deployment

---

.github/workflows/deploy.yaml

deploy deploy deploy deploy deploy deploy

deploy fixed deployment

---

flask_app.py

After I fixed the version thing, deployment is now 102% working!

Bring hotfixes back in to main

---

flask_app.py
static/main.js
vyxal/helpers.py
vyxal/main.py
vyxal/parse.py
vyxal/transpile.py

Closes #287
Closes #289
Closes #292 
Closes #293 
Also fixes a small bug with recursion in lambdas where it'd return a list instead of just the value.

Aaron's bugs fixed

---

flask_app.py
setup.py
static/css/main.css
static/main.js
templates/index.html
tests/test_transpiler.py
vyxal/LazyList.py
vyxal/__main__.py
vyxal/context.py
vyxal/elements.py
vyxal/helpers.py
vyxal/main.py
vyxal/parse.py
vyxal/transpile.py

Closes #253
Implements the ability to vectorise recursion
Fix some other things pointed out by LGTM

Recursion vectorisation and fix 253

---

vyxal/LazyList.py
vyxal/elements.py
vyxal/helpers.py
vyxal/lexer.py

The branch name means that it fixes the issues raised by Aaron:
closes #316 
closes #317 
closes #318
closes #321 
closes #322 
closes #323
closes #324

fix the bugs raised by Aaron and EmanresuA

---

vyxal/elements.py
vyxal/helpers.py
vyxal/transpile.py

Closes #325 
Closes #326 
Closes #327
Closes #328 
Closes #329 
Closes #330 
Closes #331

Bug fixes from AoC

---

static/main.js

Fixed #187

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/context.py
vyxal/elements.py
vyxal/main.py
vyxal/parse.py
vyxal/transpile.py

closes #235
closes #333
closes #344

implement #235 and #333

---

documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

closes #362 
closes #363 
closes #364

Issue fixing and Þṁ

---

documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
static/parsed_yaml.js

update them docs

---

vyxal/helpers.py

Exactly what the branch says - make `m` work with `0`

---

setup.py
vyxal/main.py
vyxal/transpile.py

Potentially fix execing things in main

---

documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Fix #389 by adding two new elements that can be used internally.

---

static/css/main.css
static/main.js
templates/index.html

Closes #408
Demo: https://youtu.be/HNsvaLAJRr4

Add HTML rendering

---

vyxal/elements.py
vyxal/helpers.py

Closes #414 
Closes #417 
Closes #419 
Closes #429

Fix a few bugs

---

vyxal/__main__.py
vyxal/elements.py
vyxal/main.py
vyxal/structure.py
vyxal/transpile.py

Just added an else branch that handles cases when rhs < lhs

Handle reversed ranges for ṡ

---

documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
static/main.js
static/parsed_yaml.js
tests/test_elements.py
vyxal/dictionary.py
vyxal/elements.py

Closes #398
Closes #413 
Closes #440 
Closes #445 
Closes #448 
Closes #457

Whole bunch of fun little bug fixes

---

vyxal/dictionary.py
vyxal/elements.py
vyxal/helpers.py
vyxal/main.py

This is quite literally me when I bugfix on tuesday

---

vyxal/elements.py
vyxal/helpers.py

Address #475 and #490

---

vyxal/elements.py

literally what the branch says

---

documents/knowledge/elements.yaml
poetry.lock
pyproject.toml
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Get rid of numpy

---

documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add direction parsing elements `¨^` and `¨□`

---

README.md
documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Update production (26/12/2021) - fix frontend keyboard

---

README.md

add vyxapedia

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Improve multiply on strings, fix right bitshift, and enhance `I`

---

documents/knowledge/elements.yaml
vyxal/elements.py

Roman Numerals

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

Implement 518

---

vyxal/elements.py

Implement #530

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
vyxal/elements.py

Make `o` do the same as `ṅ` but starting at `1` instead of `0`

---

vyxal/elements.py
vyxal/helpers.py

Fix the collect until false elements

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

implement #544

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

implement both suggestions from issue #548

---

documents/knowledge/processor.py
flask_app.py
tests/test_elements.py
vyxal/LazyList.py
vyxal/elements.py
vyxal/encoding.py
vyxal/helpers.py
vyxal/structure.py
vyxal/transpile.py

Fixed a few things to get deepsource to shut up, added some docstrings, made flake8 ignore test_elements.py

Some fixes from deepsource

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/LazyList.py
vyxal/elements.py

closes #560
closes #565 
closes #566

close #560, #565, #566

---

tests/test_complex.py
vyxal/elements.py
vyxal/helpers.py

fix #568 and #569

---

vyxal/elements.py

restore previous behaviour of division by 0 (return 0 for everything)

---

vyxal/elements.py

fix exec as python and uh turn it off online

---

vyxal/elements.py

Make Ṫ check if sympy instead of is int

---

vyxal/elements.py

fix range on numbers and strings

---

vyxal/elements.py

use wrapify instead of pop

---

vyxal/elements.py

fix gcd on strings and close #594

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Exactly what it says on the box
Closes #571

Fix #571 (Make LCM reduce on lists)

---

vyxal/LazyList.py
vyxal/elements.py
vyxal/transpile.py

remove extraneous print statements

---

vyxal/transpile.py

fix looping over the ghost variable

---

.github/workflows/linter.yaml
.github/workflows/run-tests.yaml
README.md
documents/knowledge/Elements.txt
documents/knowledge/elements.md
documents/knowledge/elements.yaml
poetry.lock
pyproject.toml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py
vyxal/encoding.py
vyxal/helpers.py

Merge after merging everything else

Update Production (18/1/2022)

---

vyxal/elements.py

Switch from checking length to yielding each collective prefix

---

vyxal/elements.py

Make logical not cast its result to a sympy integer

---

vyxal/main.py

Closes #631
<sup>Yay! My first PR in Vyxal</sup>

Add flag `l`

---

tests/test_complex.py
vyxal/LazyList.py
vyxal/elements.py
vyxal/helpers.py

I was going to straight-up copy @hyper-neutrino's implementation, but I couldn't get it work for finite lists so I rolled a naive solution of my own. Feel free to improve it.

Implement cartesian product for infinite lists

---

tests/test_complex.py
vyxal/elements.py

Addresses [this](https://github.com/Vyxal/Vyxal/pull/640#discussion_r788799857) and adds a test.

Make copy of prefixes, add test

---

tests/test_complex.py
vyxal/elements.py

I have no idea how it would ever work if `rhs` is an infinite list, though. This basically does half of [this](https://github.com/Vyxal/Vyxal/issues/600), though.

Let F work when lhs is an infinite list

---

documents/knowledge/elements.yaml
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Exactly what emanresu suggested, suffixes of prefixes

Implement sublists for infinite lists

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

I was working on [this](https://github.com/Vyxal/Vyxal/issues/586) but the issue for `Ḟ` has already been fixed 😂

Add test for Ḟ with an infinite list

---

tests/test_complex.py
vyxal/elements.py

Make `Þf` work for infinite lists

Use generator for shallow flatten

---

tests/test_complex.py
vyxal/helpers.py

fix the base_conversion helper thingy

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Just added a test and clarified the swapped overload

Ensure Þs works with infinite lists (it does)

---

tests/test_complex.py
vyxal/elements.py

Closes #668 
I swear I know how to write an esolang. Don't judge me because I accidentally used the wrong names in a `for` loop for several releases.

Fix min-by and max-by function

---

vyxal/elements.py

Make `vy_repr` account for the `P` flag

---

vyxal/elements.py
vyxal/lexer.py
vyxal/main.py
vyxal/transpile.py

Implement the V flag

---

static/main.js

autofocus the code box

---

tests/test_complex.py
vyxal/helpers.py

Fix bool input

---

tests/test_complex.py
vyxal/elements.py

Implement monadic filter

---

vyxal/transpile.py

and so are a bunch of other types too

nilads are numbers too

---

tests/test_complex.py
vyxal/elements.py

Fix vectorised nilads

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add: shortest of a list (`Þg`), longest of a list (`ÞG`) and sort by length (`Þṡ`)

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

Fix c and l flags

---

vyxal/elements.py
vyxal/helpers.py

Make integer equality great again.

---

vyxal/LazyList.py
vyxal/main.py

Fix the `j` flag

---

tests/test_complex.py
vyxal/elements.py

This is kinda like cartesian product, it goes diagonally (or whatever the word for multidimensional diagonals is). This implementation is only used for `LazyList`s because it's probably inefficient; lists use the original one.

Implement cartesian power for infinite lists

---

tests/test_complex.py
vyxal/elements.py
vyxal/helpers.py

Closes #748 
Honestly idk why on earth you'd need this, but as you wish.

As requested, `*` now vectorises if there's a function

---

vyxal/elements.py

Make `∆f` vectorise

---

vyxal/elements.py

This fixes a bug where `¨U` gets a 403 because of the wrong user agent.

Added User-Agent

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add First n Items and Rest element

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Make Π do the same as Þ* when not given a list of numbers

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
vyxal/elements.py
vyxal/parse.py

Based on @pxeger's suggestion in #741
And yes, you can have modifiers that are also digraphs. Believe it or not, I wrote the parser with digraphic modifiers in mind.

Add ¨= modifier (is equal after applying)

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Add ÞN (alternating negations) element

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add Sorting Digraphs (ÞṠ, ÞṘ, ÞȮ, and ÞĊ)

---

vyxal/main.py
vyxal/transpile.py

closes #776 
Now eg. `{n,` outputs:
```
1
2
3
...
```
Should the counter start at 1?

Add while loop counter

---

vyxal/elements.py

Patch vy_repr on strings

---

vyxal/elements.py

Make Ṁ insert in multiple places if given a list

---

tests/test_lexer.py
vyxal/lexer.py

Tokenise `x.` as `x.5`

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Implement k•

---

vyxal/elements.py

Make `øM` vectorise

---

vyxal/elements.py

E.g.
- Make the argument order make more sense for some regex dyads
- Make some dyads not error if there isn't a match

Fix a bunch of regex stuff

---

vyxal/LazyList.py
vyxal/elements.py

Also, add an `is_empty` method to `LazyList`

Improve the functionality of the rotate elements

---

vyxal/elements.py
vyxal/helpers.py

And fix the errors resulting from that
Closes #804

Make `?` turn numbers into sympy numbers

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Add rearrange at indices overload to `¢`

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
vyxal/elements.py

Improve the documentation of `¨M`

---

vyxal/main.py

Make the implementation of the `S` flag on LazyLists better

---

pyproject.toml

Version 2.10.0

---

vyxal/LazyList.py
vyxal/elements.py

Make lazylists immutable

---

vyxal/elements.py

Change the functionality of ẇ

---

vyxal/elements.py

Improve the functionality of the ḋ flag

---

tests/test_complex.py
vyxal/transpile.py

Make empty lists _not_ contain the top of the stack

---

vyxal/elements.py

Make `vy_exec` vectorise properly on strings.

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

Quick ACE mitigation since I don’t have time to actually fix it right now.

Temp ACE Fix

---

documents/knowledge/yaml_to_js.py
static/parsed_yaml.js

the worstest possible way to fix the keyboard

---

documents/knowledge/yaml_to_js.py
flask_app.py
static/parsed_yaml.js

fix keyboard

---

.gitignore
documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add keep truthy overload to bitwise not

---

vyxal/main.py

Document some flags that were missing

---

tests/test_lexer.py
vyxal/lexer.py

Make backslashes at the end of a 2 character string include the backslash

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

- makes starts with work with lists
- add ends with
- add starts with set
- add ends with set
Closes #900 and closes #901.

Starts with and ends with

---

vyxal/main.py

fixes issue where it no work [here](https://vyxal.pythonanywhere.com/#WyJzIiwiIiwiVMKmduKCgyIsIiIsIjI2MDQyIl0=)
[user was right that he caused it](https://github.com/Vyxal/Vyxal/commit/d1f329de0f2db87c97de36620fc28d57c76c92d8)

fix sum flag when it is lazylist

---

documents/knowledge/elements.txt
documents/knowledge/elements.yaml
vyxal/elements.py

Make øṀ vectorise on lists

---

vyxal/parse.py

Make parser account for _all_ literals

---

vyxal/elements.py

#474 
`optimal_compress` in `elements.py` now considers the small dictionary when compressing strings

Add short dictionary into optimal compression

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

Add the string overload of ṅ to the YAML

---

vyxal/elements.py

Fixes #952
<s>(don't merge yet, I'm going to add a test or something)</s> Never mind, I'll just run it on my computer once.

Don't use eval for datetime stuff

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

ok, who taught yall english?

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Add group by function overload to ġ

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

closes #908 
man this is teaching me to use British spelling...

add elements for palindromise, center, and join on newlines, and also same for mirror

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py
vyxal/parse.py

Closes #996
Also: PR/issue #1000! 💯

Add modifier to run for each overlapping pair

---

vyxal/elements.py

Vectorization would have been completely broken for these as well.
Closes #1013.

Fix round, is_square, and is_prime

---

tests/test_complex.py
vyxal/elements.py

Fixed lift on infinite lists

---

tests/test_complex.py
vyxal/elements.py

Fix find on infinite lazylists

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Allowed swapped args for l

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Fixes #861 
Also works for lists because it's cool

Added surround

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

added ඞ unicode

---

tests/test_complex.py
vyxal/elements.py
vyxal/transpile.py

Fixes #1041 according to #1047

Improve generator behaviour

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Cycle builtin

---

vyxal/elements.py

Fix print with space without popping

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add element to divide list into n parts

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add overload to get real and imaginary parts of complex number to round

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add element to fill matrix to make it rectangular

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py

Make coords_deepmap a monograph

---

vyxal/context.py

Make register and nameless variable run through sympy before being set

---

.github/workflows/greetings.yml

It's a Github action that greets users when they create an issue or a PR.
I'm bad at making up greeting messages.

Add greetings action

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

Closes #1098
It seems that when I first implemented it, I didn't actually get the right definition of matrix exponentiation. I had the matrix plain multiplied by itself n times instead of using the actual matrix multiplication function.

Make Matrix Exponentiation work properly

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

No linked issue, something found after conversation in TNB.

Make `F` not error when given an integer as rhs

---

templates/index.html

Fix search

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
documents/specs/Documentation.md
static/parsed_yaml.js
tests/test_elements.py

and edit the spec for element docs

Improve element docs

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/LazyList.py
vyxal/elements.py

Add infinite list of all integers

---

vyxal/elements.py

Improve the behaviour of `ŀ`

---

vyxal/elements.py

Improve the behaviour of `Ḋ`

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
vyxal/elements.py

Fix random choice (`℅`)

---

vyxal/elements.py

Fix head remove with negative numbers

---

documents/knowledge/elements.yaml
tests/test_elements.py

Remove a test case that was actually invalid

---

vyxal/elements.py

Fix split and keep delimiter

---

vyxal/helpers.py

This should work without mutable lists. All tests work.

Fixed mold (I think?)

---

vyxal/elements.py

Make `O` work when given a string and number and vice-versa

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py

Change element name of `Þ÷` for clarity

---

flask_app.py
static/main.js
static/search.js
static/tooltip.js
templates/index.html

in preparation for #1116, we:
- split the frontend js into several files
- remove jquery (it's 2022, seriously)
- defer scripts to decrease blocking loading time

refactor frontend

---

vyxal/elements.py

Goes towards closing #1164 
Merge after #1197 as this relies on a fix in that PR

Make insertion leave numbers as numbers

---

vyxal/elements.py

Make `Ẏ` and `Ż` leave numbers as numbers

---

tests/test_complex.py
vyxal/context.py
vyxal/main.py
vyxal/transpile.py

Fixes #1196. Also cleaned up transpilation options

Utf8 strings

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Closes #1181
Lyxal did this not me but apparently forgot to make a PR

Add a is strictly ascending and is strictly descending elements

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Add take while overload

---

vyxal/elements.py

The code's a lot cleaner and less repetitive now.
Everything in test_complex.py passes, and it seems to work overall, but I may have broken some other stuff. Review with caution.

cleaned up vectorise

---

tests/test_complex.py
vyxal/elements.py
vyxal/parse.py

By making the parser parse it as an if statement.  Fixes #1182

Fix conditional execute

---

static/css/main.css

Make tooltips unselectable

---

vyxal/main.py

I actually tested this with the flask_app.py and it works.

Actually fix A flag

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Add drop while overload

---

vyxal/elements.py
vyxal/helpers.py

Make `⌊` account for decimals and negatives

---

vyxal/elements.py

Fix untruth

---

vyxal/LazyList.py

Fixes #1242
Btw this code is really DRY

Fix strings without quotes

---

static/css/main.css
static/keyboard.js

conflicts with #1257 and i prefer that get merged first
also adjusts threshold for search results

Tooltip highlights

---

vyxal/LazyList.py

Fix issue where negative indexing into LazyList appends to itself

---

vyxal/elements.py

Fix that ∆F vectorizes on ∆f

---

vyxal/LazyList.py

Fix boolify on LazyLists when raw_object is exhausted

---

vyxal/elements.py

No linked issue, just a broken test

Fix arrow parsing elements

---

vyxal/elements.py

Make `ÞS` respect original type

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

No linked issue, just a test that wasn't passing.

Make `€` work properly again

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add "truthy under" overload to T updot

---

tests/test_complex.py
vyxal/transpile.py

Fix nested modifiers' arity

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py

No linked issue, just a test that forgot to be changed.

Fix last failing test

---

static/main.js

Allow tab string compress

---

vyxal/elements.py

Remove duplicated functions

---

vyxal/elements.py
vyxal/helpers.py

Make `vy_floor` work properly with strings.

---

tests/test_transpiler.py
vyxal/elements.py
vyxal/helpers.py
vyxal/transpile.py

So apparently we changed vy_floor but not the thing that actually pushes numbers

Make numbers work right

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add count overlapping element

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Add adjacent filter-group

---

vyxal/elements.py

Preserve string state with shuffle

---

vyxal/elements.py

Make İ never include the initial value

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

Fix docs for ↔ and İ

---

static/main.js

When generating a CGCC post template, don't show some flags

---

tests/test_complex.py
vyxal/elements.py

Fix assign

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add next/prev power builtins

---

.github/labeler.yml
.github/workflows/labeler.yml

It didn't work yet, this is why

Fix issue labeler

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py

Add element overloads for maximums/minimums by

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Make `İ` make complex numbers

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add a next multiple element (`∆*`)

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Make `Ḣ` rangify

---

.github/workflows/labeler.yml

Finally fix labeler

---

vyxal/context.py
vyxal/elements.py
vyxal/main.py

Fix all inputs

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add element to gridify

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Add `Þ:` and add a bit more description to `Þ∞`

---

tests/test_complex.py
vyxal/helpers.py

Make lambdas be available to take via normal input

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add hyperbolic trig functions

---

tests/test_complex.py
vyxal/helpers.py

Make mold no longer return weird outputs

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py

Add first truthy non-integer and n truthy non-integer overloads

---

tests/test_complex.py
vyxal/elements.py

Make cumulative sum on infinite lists work again

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Add multi-dimension enumerate and multi-dimension indices

---

tests/test_parser.py
vyxal/parse.py

Make sure tokens after a modifier have the appropriate parent

---

vyxal/elements.py

<insert disapproving lenny face here>

Make ¨U work NOT online but offline

---

tests/test_complex.py
vyxal/elements.py

Time to see if the workflows actually let the tests work
Closes #1464

Make web requests work again

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

Update documentation for very last and second last input

---

vyxal/dictionary.py

Add some contractions to the dictionary

---

tests/test_complex.py
vyxal/main.py
vyxal/transpile.py

Make variadic functions work again

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Make `∆²` parenthesize argument

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

Make permutations not join sublists when given list of strings

---

.gitpod.Dockerfile
shared/src/main/scala/Context.scala
shared/src/main/scala/Globals.scala
shared/src/main/scala/Inputs.scala
shared/src/test/scala/ElementTests.scala
shared/src/test/scala/InterpreterTests.scala

Made a `Globals` class with inputs, settings, and a register. Every `Context` can hold a reference to the same `Globals` object to share global inputs and stuff.

Make provisions for globals

---

tests/test_complex.py
vyxal/elements.py

Make `&` work properly with dyads

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/elements.py

Make øṄ account for overlapping matches

---

.github/ISSUE_TEMPLATE/bug_report.md
vyxal/dictionary.py

Add "scissors" to the dictionary

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

Implement Reduced Echelon Form

---

.github/workflows/lint.yaml
.scalafix.conf
shared/src/main/scala/Elements.scala
shared/src/main/scala/ListHelpers.scala
shared/src/main/scala/MiscHelpers.scala
shared/src/main/scala/Parser.scala
shared/src/main/scala/VNum.scala

Just turning `.size == 0` into `.isEmpty` and removing `: VAny`

Minor changes according to custom scalafix rules

---

tests/test_complex.py
vyxal/elements.py

Fix a logic error with apply at

---

README.md
build.sbt
documentation/Context.md
documentation/ElementDocumentation.md
documentation/Interpreter.md
documentation/ModifierImpl.md
documentation/README.md
documentation/Tests.md
documentation/UsingSBT.md
shared/src/main/scala/Context.scala

Made a file for explaining how to use sbt. Need to update element implementation docs and add docs on how to write tests.

Write some more docs for v3

---

.github/workflows/greetings.yml

Improve greetings.yml

---

sort_element_functions.py
vyxal/elements.py

Adds an element decorator so that elements that have a function for them and a fixed arity don't have to be manually added to the elements dictionary. Perhaps eventually, we could also use this to completely replace elements.yaml (other than the tests)

Add element decorator

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

Make `℅` state it's 1 to n, not 0 to n in the docs

---

documentation/elements.txt
jvm/src/main/scala/Main.scala

Sort element docs by place in codepage

---

.github/workflows/scalafix.yaml

Removed the `--check` so that Scalafix actually fixes stuff, copied the auto commit stuff from the test-build workflow.

Actually make changes in lint workflow

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

Add a convolve element that behaves like Jelly's

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/LazyList.py
vyxal/elements.py

Closes #1649 and does some other things

Improve some comparison-related functions

---

shared/src/main/scala/Lexer.scala
shared/src/main/scala/LiterateLexer.scala
shared/src/test/scala/LexerTests.scala
shared/src/test/scala/LiterateTests.scala

(Version 3): Make _ part of number syntax

---

documentation/elements.txt
shared/src/main/scala/Elements.scala
shared/src/main/scala/Lexer.scala
shared/src/main/scala/LiterateLexer.scala
shared/src/main/scala/MiscHelpers.scala
shared/src/test/scala/ElementTests.scala

Add E to elements

---

documentation/elements.txt
shared/src/main/scala/Elements.scala
shared/src/test/scala/ElementTests.scala

Implement J element for version 3

---

documentation/elements.txt
shared/src/main/scala/Elements.scala
shared/src/main/scala/ListHelpers.scala
shared/src/test/scala/ElementTests.scala

Implement the `I` element in version 3

---

vyxal/elements.py

Make Ǔ/ǔ modular

---

vyxal/dictionary.py

Add the word "bingus" to the dictionary

---

vyxal/context.py
vyxal/elements.py

Add some default values to some nilads

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
tests/test_parser.py
vyxal/elements.py
vyxal/parse.py

Based on an observation by @jfioasd in #14

Make `@` vectorised lengths

---

vyxal/elements.py

Postpones #1486
This is temporary while we wait for something to come up that would be useful

Make `G` and `g` NOPs on Numbers

---

documentation/elements.txt
shared/src/main/scala/Elements.scala
shared/src/main/scala/NumberHelpers.scala
shared/src/main/scala/VAny.scala
shared/src/main/scala/VList.scala
shared/src/test/scala/ElementTests.scala

Implement H

---

vyxal/helpers.py
vyxal/main.py

Reverse order of output of `~`

---

vyxal/elements.py

Quick patch on the code I wrote for `R`

---

vyxal/elements.py

https://vyxal.pythonanywhere.com/#WyIiLCIiLCLiiIZNIiwiIiwiW10iXQ==

Make `∆M` not error on an empty list

---

documents/knowledge/elements.yaml
tests/test_elements.py
vyxal/helpers.py

Closes #1694 (hopefully)
I'm not sure if this will work, but let's give it a try anyway.

Attempt to fix #1694 (Transpose bug)

---

vyxal/context.py
vyxal/main.py

Let's see how this goes...
Fixes #1703

Fix `~` flag not working with other flags

---

shared/src/main/scala/NumberHelpers.scala

Apply late suggestions on another PR

---

.gitattributes

Update .gitattributes (v3)

---

shared/src/main/scala/Elements.scala
shared/src/main/scala/ListHelpers.scala
shared/src/main/scala/MiscHelpers.scala
shared/src/test/scala/ElementTests.scala

Version 3: Implement G element (maximum)

---

pyproject.toml

Version 2.21.0

---

templates/index.html

Don't defer popper

---

documentation/elements.txt
shared/src/main/scala/Elements.scala
shared/src/main/scala/ListHelpers.scala

Add prefixes element

---

static/main.js

Needs linting and testing because I wrote it on mobile.

Remove html from cmc bit link and improve vyncoded cmc link formatting

---

pyproject.toml

Version 2.21.1

---

vyxal/main.py

See [this chat message](https://chat.stackexchange.com/transcript/message/63531252#63531252) by emirps.

Make A flag not give the LazyList repr for set inputs

---

shared/src/main/scala/VList.scala

Closes #1743. This isn't my fix, this is @shaiksamad's fix.

Fix VList.from (@shaiksamad)

---

static/main.js

Put the link in the superscript not the bytes

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
tests/test_elements.py
vyxal/elements.py

Not inspired by a recent code golf challenge totally not.

Add uniquify by function overload to ε

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

I swear there's been cases where it's been a problem to not have non-modular indexing

Add non-modular indexing

---

README.md

Code:
```
import vyxal.main
vyxal.main.execute("file","flags","input")
```
This merge will add this to `README.md`.

Document python function to run vyxal code

---

documents/specs/Lexer.md

change <code>`hello`</code> to <code>\`hello\`</code>

Fix formatting error

---

vyxal/elements.py

Fix the printing of complex numbers

---

.scalafmt.conf

Update scalafmt-core to 3.7.6 in version-3

---

pyproject.toml

Version 2.21.4

---

vyxal/elements.py
vyxal/helpers.py

Now you can use the β element with lists!
Implements issue #1829 .

Make β work with lists

---

pyproject.toml
vyxal/main.py

Friendship with tomllib ended. We using importlib.metadata now

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
refresh
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py
vyxal/helpers.py

I had to resort to having tuples containing the index of the item.

Add element to parse string using alphabet

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_elements.py
vyxal/elements.py

I'm surprised Vyxal does not have this yet!

Add SHA256 hash function

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

https://chat.stackexchange.com/transcript/message/64104750#64104750

Change wording of `¹`'s description

---

vyxal/LazyList.py

Add a `.find` and `.index` method to `LazyList`

---

vyxal/transpile.py

Hopefully fix compressed numbers not sympifying

---

vyxal/main.py

Seems this is needed.
Closes #1854

Add sympy import

---

pyproject.toml
vyxal/transpile.py

Update Production (14 August 2023)

---

README.md

Just `pip install git+https://github.com/Vyxal/Vyxal@main` in a virtual environment.

Add another way to test the code

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js
tests/test_complex.py
vyxal/elements.py

Add two more collector functions

---

shared/src/vyxal/Elements.scala
shared/src/vyxal/ListHelpers.scala
shared/test/resources/tests.yaml

Start to add L downdot

---

pyproject.toml

Update pyproject to 2.21.10

---

README.md

Highly open to suggestions, rewordings and other contributions

Actually write the readme

---

documents/knowledge/elements.md
documents/knowledge/elements.txt
documents/knowledge/elements.yaml
static/parsed_yaml.js

Correct documentation for enumerate to mention it starts at 0

---

shared/src/vyxal/MiscHelpers.scala
shared/src/vyxal/parsing/Parser.scala
shared/test/src/vyxal/ParserTests.scala

It was broken when switching to fastparse it seems.

Fix an issue with variable unpacking

---

js/src/vyxal/JSVyxal.scala
shared/src/vyxal/CLI.scala
shared/src/vyxal/parsing/Parser.scala

Make the online interpreter, and CLI input args evaluate lists properly

---

.scalafmt.conf
build.sbt
build.sc

Maybe this makes the workflows work?

---

README.md

Array language terminology

---

documentation/table.md
js/src/vyxal/JSVyxal.scala
shared/src/vyxal/CLI.scala

Add an endpoint to get the version

---

vyxal/helpers.py

Make table not return a generator
