- templates/main.html
Since output is now a textarea its value should be updated, not its innerHTML. tested in the console by overwriting the js function and it worked out fine
> Change "innerHTML" to "value"

- Vyxal.py
`header` didn't have a newline at the end of it, so the first line of `compiled` was being appended to the last list of `header`, giving output like:
```
aaron@localhost:~/Vyxal$ python Vyxal.py test c
stack = []
register = 0
printed = Falsestack.append(42)
Traceback (most recent call last):
File "Vyxal.py", line 2479, in <module>
exec(code)
File "<string>", line 3, in <module>
NameError: name 'Falsestack' is not defined
```
Also made it so that the `I` command can cast complex number to real numbers by removing the imaginary part, similar to casting floats to ints by removing the decimal part. (These were supposed to be two separate PRs, but I accidentally made them into one.)
> Fixed bug with offline interpreter failing to execute

- Vyxal.py
It turns out, this flag was really simple to implement. Also added consistency between `'X' in flags:` and `"X" in flags:`
> added D flag for raw strings

- VyParse.py
Fixed bug where a number with multiple decimal points would only push the number up to the first decimal, e.g. 
```
123,          || 123       // Expected
123.456,      || 123.456   // Expected
123.456.,     || 123       // Not Expected
123.456.789,  || 123       // Not Expected
```
This bug only affects the offline interpreter, though I don't understand why.
> fixed offline integer parsing bug

- VyParse.py
- Vyxal.py
- commands.py
- docs/elements.md
- docs/elements.txt
There was a parsing bug where a string at the end of an integer or a variable name would be parsed as part of it, e.g.
```
123.456`hello`789
```
This program tries to convert ```123.456`hello`789``` to a float, which errors. 
```
42→x`world`
```
This program tries to assign `42` to a variable named ``` x`world` ``` which also errors.
Now, the first program pushes `123.456`, `hello`, and `789` to the stack. The second program assigns `42` to a variable named `x` and pushes `world` to the stack.
> strings and structures decided to get along

- Vyxal.py
- commands.py
Fixed #64
Test program:
```
`Hello, World!`qĖ,
389qĖ,
4.3qĖ,
`\\t\\`qĖ,
`\\\`\`\\\\`qĖ,
`\
`qĖ,
`--------`qĖ,
`--------`,
`Hello, World!`,
389,
4.3,
`\\t\\`,
`\\\`\`\\\\`,
`\
`,
```
> `uneval` is now `uneval` and can be `eval`ed to un`uneval`

- Vyxal.py
Fixed. Summing empty list now returns 0.
> Bugfix - summing empty list throws error

- Vyxal.py
`₅` was broken for strings, throwing an error because it couldn't serialise a tuple to an int. This has been fixed.
Addtionally, `₂`, `₃`, and `₅`  (respectively `len(a) % 2 == 0`, `len(a) == 1`, and `a, len(a)`)  work for lists now, with exactly the same functionality as on strings.
> Fixed ₅ for strings, ₂₃₅ work for lists now 

- commands.py
It seems the parens are mismatched in the generated code for `øṀ`
> Typo in `øṀ`

- Vyxal.py
All hail flake8, which pointed out that types wasn't defined on line 1094 (now line 1095).
> Define types in join_on

- templates/main.html
When using UTF-8 encoding, entering a single non-ASCII character will cause the byte count to read "<N> byte", where N is not 1. This is because the pluralization was determined by the code length rather than the encoded UTF-8 bytestring length.
> fix pluralization bug when using UTF-8 encoding

- Vyxal.py
- dictionary.py
- words.py
Previously, `word_index` used `_words.index` to find the index of the word in the dictionary, which is extremely slow. Now, a hashtable is pre-built to convert `word_index` to a constant-time function.
> Use hashtable to speed up string compressing very significantly

- vyxal/array_builtins.py
As per #146 this implements cartesian product that works with generators. The order is not exactly consistent; however, unlike currently, it will actually return every element (it is not possible for this to be consistent), with generators on the left, right, or both.
> implement generator-friendly cartesian product

- documents/protocols/contributing.md
- documents/protocols/security.md
To do:
- Probably add some more wording and stuff
- Decide on which email address(es) to use for this. I'd like to be on there though because I am a 1337 h4xx0r world class security expert
- Perhaps mention that trying to attack the official online interpreter is, ahem, *illegal*?
> Add a security policy

- vyxal/structure.py
Also renamed `Structure.py` to `structure.py` because all the other files are lowercase.
> Use CamelCase instead of both camel case and snake case in class names

- templates/main.html
I wouldn’t want my code to disappear when I want to, say, look up a command or star the repo.
Note that I haven’t tested if this works yet but it probably works
> Made link open a new tab

- scripts/vyxal
- setup.py
- vyxal/__main__.py
- vyxal/context.py
- vyxal/helpers.py
- vyxal/transpile.py
Basically just the CLI - there's still flags that need implementing, but those can be done on the `pr-272-suggestions` branch.
> Cli implementation

- documents/knowledge/elements.yaml
where it says `a ** 2`, and it literally says two lines down `2 ** a` (and vyxal actually does `2 ** a`)
> Corrected documentation for `E`

- vyxal/elements.py
Use `factorial(abs(x))` so that negative numbers don't go boom.
> Use abs for factorial of negative numbers

- vyxal/elements.py
There were two extra `ctx` arguments given to `str.strip` inside `def strip()`/element `P`, this is just a trivial thing removing those. I haven't run any tests, but it probably works.
> Remove unnecessary ctx argument to strip in P aka strip

- vyxal/context.py
- vyxal/elements.py
- vyxal/helpers.py
- vyxal/main.py
Closes #304 
Closes #352 
I also fixed a little division by 0 error I noticed - it's just implementing the behaviour that already exists in 2.4 and has proven to be useful: `0 / 0 = 0` for golfing purposes.
> Make the stack pad with 0s if no input offline, and fix an issue with set operators

- vyxal/elements.py
`k⟇` was implemented as `codepage` instead of `vyxal.encoding.codepage` (which is not imported). Trivial fix.
> Use 'vyxal.encoding.codepage' instead of 'codepage' for k⟇

- vyxal/elements.py
We had a bunch of  debugging `print`s in various functions, which was causing IO errors on the online interpreter.
> Removed a bunch of prints causing weird errors

- .gitattributes
Whenever `elements.yaml` changes, I always see `Elements.txt` first and comment on that before realising it's not the source file. By marking these files as `linguist-generated=true` in a `.gitattributes` file, they will be excluded from GitHub diffs, and this won't happen.
See https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
> Hide generated elements files from GitHub diffs

- static/main.js
Closes #407.
Hopefully this series of popups is good enough to prevent self-XSS.
> Add eval as JS option

- vyxal/transpile.py
To check if a variable is equal to one of many values, combine the values into a tuple and check if the variable is contained `in` it instead of checking for equality against each of the values. This is faster, less verbose, and more readable.
> Fix deepcover PYL-R1714 issues

- vyxal/main.py
Closes #441.
I also added a note about the `E` and `Ḣ` flags.
> Clean up flags help

- .github/workflows/run-tests.yaml
It was called `build` which was kinda confusing; now it's called `test`
> Rename step in testing workflow

- documents/knowledge/elements.yaml
- tests/test_elements.py
- vyxal/elements.py
This PR adds `Þ*` as a digraph to do cartesian product over a list like Jelly (note that this isn't the same as reducing with cartesian product, so a new digraph was necessary). The actual symbol used for the digraph can of course be changed, this PR is really just to implement it. It doesn't handle generators because cartesian product over a possibly infinite list of possibly infinite lists is gonna be really complicated.
Closes #446
> Make cartesian product over list (Þ*)

- .github/workflows/pypi.yaml
You will soon be able to do `pip install vyxal` with no further details. Closes https://github.com/attempt-this-online/attempt-this-online/issues/6 (CC @Lyxal)
This needs to be pulled into `main`, tested with a placeholder tag (I suggest `v2.7.2post1`), and if/when it works:
1. remove the `repository_url` so it uses the real PyPI
2. replace the PyPI token with one that has permission to upload to the `vyxal` package namespace
- I suggest I own that package initially and then once I've got it all working I'll grant permissions to people (you'll need PyPI accounts!)
> Add GitHub actions workflow to build and publish package to PyPI

- vyxal/elements.py
- `vy_eval` wasn't being called with a context argument in one place
- lgtm was complaining about a non-callable being called so I shut it up
> Heed an LGTM alert

- README.md
This will keep only the lgtm code quality badge (because it looks nice if we have A quality code) and the tests badge (because it's important for our code to run). PA deployment can be seen on the right in the Environments section, I think. We're not gluten free anymore because of sympy, and we don't want people seeing how many LGTM alerts we have.
> Remove a few badges

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_complex.py
- tests/test_elements.py
- vyxal/elements.py
For some reason, `øṁ` wasn't actually in the dictionary even though it was implemented.
> Add øṁ to elements dict, add test for it

- tests/test_complex.py
- tests/test_parser.py
- vyxal/parse.py
- vyxal/structure.py
- vyxal/transpile.py
Instead of immediately splitting map, filter, and sort lambdas into two elements (the lambda and the operation after it), this adds a field `after` to the `Lambda` class itself that will contain an element to be run after the lambda (or be `None` if it's a normal lambda). Then, in the transpilation phase, a call to the `after` element is added for those three special lambdas. This allows stuff like `⁽ƛ....;` to work, because previously, the lambda and the call to `M` were held as separate elements.
> Handle desugaring of lambdas in transpiler instead of parser

- tests/test_complex.py
- vyxal/elements.py
- vyxal/encoding.py
- vyxal/helpers.py
- vyxal/parse.py
- vyxal/structure.py
- vyxal/transpile.py
My "fix" for map lambdas not being taken as single elements earlier actually broke this. Now I've made a `LambdaOp` class that's separate from the `Lambda` class. Let's hope it works properly now.
Also, mypy found over a hundred errors :(.
> Separate map/filter/sort lambdas from normal lambdas

- vyxal/elements.py
> add extra calls to iterable

- documents/knowledge/processor.py
- tests/test_complex.py
- tests/test_elements.py
- vyxal/LazyList.py
There's probably still some wonkiness left with `LazyList`, but not making copies of the underlying generator and stuff should help. This should fix overdot-H (tail/remove first). It should also allow you to do `bool(somelazyilst)` without worrying about whether or not it's infinite, because there's now a separate `__bool__` method.
> Don't clone the raw object in LazyList

- tests/test_complex.py
- vyxal/LazyList.py
Add comparison functions (`__lt__`, `__gt__` etc) for lazylists to allow sorting by lazylists and comparing them in other contexts without errors.
> Add comparisons for lazylists

- tests/test_complex.py
- vyxal/elements.py
Uses `iter()`, lemme know if there's a nicer way.
todo Once this is merged, the corresponding task in the [big builtins checklist](https://github.com/Vyxal/Vyxal/issues/586) should be ticked off.
> Make interleave (Y) work on infinite lists

- tests/test_complex.py
`ȯ` was already fixed for infinite lists, this just adds a test for it
> Add test for slicing to end of infinite lists

- tests/test_complex.py
- vyxal/elements.py
Lets `≈` work for infinite lists that are not all equal (doesn't work for infinite lists that are all equal, of course).
> Don't use len in all-equal

- vyxal/helpers.py
This doesn't really fix #599, because I have no idea how you would handle it for all infinite lists, but at least this makes the output lazy and not a list.
> Make ↔ *partially* work with infinite lazylists

- tests/test_complex.py
- vyxal/elements.py
Both the list-int and list-fun overloads
> Make `ẇ` work with infinite lists

- static/main.js
fixes #367. i think.
i'm not the best person to ask considering i usually avoid jQuery like the plague, but the `$(document).ready()` method seems finicky here for whatever reason? i loaded the permalink to [Lyxal's most recent CGCC answer in Vyxal](https://codegolf.stackexchange.com/questions/63442/fibonacci-fizz-buzz-fibo-nacci/241719#241719) 25 times before and after the change; the code failed to autorun 13 out of 25 times using jQuery's method, and succeeded 25 times in a row using a plain old event listener.\
extra review from others to corroborate these findings would be appreciated; there is virtually no change to behavior as far as i can tell.
> replace jQuery ready method with regular event listener

- static/main.js
fixes #449.
line 213 is moved into a `try`/`catch` block, and `res.stdout` gets set to the result of the `catch` if necessary.
> wrap online res.stdout setter in try/catch block

- vyxal/LazyList.py
- vyxal/main.py
The good news is that this PR will let `j`, `S`, and `s` work with infinite `LazyList`s. The bad news is that with finite `LazyList`s, it immediately prints them and breaks out of the loop instead of composing other flags on top of those joining flags. I think that's a fine trade-off but obviously y'all should decide whether or not that's okay.
I was an idiot and moved stuff around so the diff is hard to understand, but just look at the if statements for `j`, `S`, and `s` in the flag loop and the `output` method for `LazyList`. Nothing else has really been touched.
> Make some joining flags kinda work with infinite LazyLists

- tests/test_parser.py
- vyxal/parse.py
> Make `|` parse correctly when its in a structure

- tests/test_complex.py
- vyxal/LazyList.py
- vyxal/elements.py
- vyxal/helpers.py
Fixes #732. This is probably much more inefficient than before, but it should work for finite lists of finite lists, finite lists of infinite lists, infinite lists of finite lists, and infinite lists of infinite lists.
> Make transpose work with infinite lists

- vyxal/elements.py
The tests for bitwise operators all fail because sympy `Integer`s are passed into them (even if they work online). It's better to turn all numbers received by those methods into `int`s first to avoid this sort of thing.
> Convert to int before applying bitwise ops

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
- vyxal/helpers.py
Implements the last part of #807. `Þd` for distance of directed matrices and `Þw` for distance of undirected matrices. We need a better symbol for the second one, though.
> Add distance matrix elements

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
Closes #859
- `øF` isn't documented because it was more of a joke and should probably be removed.
> Document `∆I` and `¨ẇ`

- tests/test_parser.py
- vyxal/parse.py
> Make it so that `x` or `X` after a modifier functions correctly.

- vyxal/elements.py
> Make `ẇ` not return a trailing empty string if nothing to split upon

- vyxal/elements.py
Closes #910
I honestly don't know how this happened.
> Make ṡ return a Lazylist object instead of a range

- vyxal/elements.py
- vyxal/helpers.py
This is not good practice at all, but this PR also makes `<<` turn its arguments into `int`s before doing the bit shifting.
For `min_by` and `max_by`, if the list is empty, it returns 0.
> Make callers of foldl work with empty lists

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
> Make `Ǐ` no longer vectorise by default 

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
- vyxal/helpers.py
Will eventually close #971. Also modifies `enumerate_md` to act more like Python's enumerate (yields tuples `(index, item)` instead of just indices)
> Implement all indices

- vyxal/elements.py
- vyxal/helpers.py
This is because, somehow, `LazyList`s' `__bool__` evaluates to `False`, but idk how to fix that, so this does the job.
Fixes #997.
> Fix G and g

- tests/test_complex.py
- vyxal/elements.py
Closes #1001 
Can't believe I have to type 4 digits now when using closing keywords. What a hassle :p
> Make `ẏ` and `ż` work on infinite lists

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
Fix #937 by reimplementing `ẇ` from the ground up.
Now, there's sensible behaviour on all types, where before several overloads were broken or produced cursed results.
In particular, string lists will return (lists of) string lists, ***not*** concatenate them. Also, some overloads will work both ways. Don't worry, it doesn't break anything.
> Finally fix ẇ

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
And other stuff
Fixes #958 
`ε` now has some flash new overloads as well - str-num creates an array of strings with a certain length, str-str does a single regex match.
> Make abs diff vectorise

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_complex.py
- tests/test_elements.py
- vyxal/elements.py
- vyxal/helpers.py
It used to not preserve order. this also makes a string return a list of strings
> Fix group by

- static/main.js
`event.metaKey` is ctrl on Windows and cmd on Mac.
> Made ctrl/cmd + enter work on Mac

- tests/test_complex.py
- vyxal/elements.py
No related issue, just something that came up in chat.
> Make the arguments of `ß` go in the right order

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
#1119 marked `i`'s behavior when given `1357, [1, 3]` as a bug, but it's a feature (for real this time). There's a `num-any` overload that does `b[a]`. It and the `str-str` overload are now documented and each have a test.
> Fix the mysteriously failing `i`

- tests/test_complex.py
- vyxal/parse.py
It simply appends the second element as an identity function.
> Fix dyadic modifiers when used monadically

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/context.py
- vyxal/elements.py
`ÞẊ` now turns string arguments into lists of characters and turns numbers into ranges. The docs and tests for both now reflect this.
> Fix tests for `Ẋ` and `ÞẊ`

- vyxal/elements.py
It was erroring because `max` was being passed an empty list.
> Make depth (`Þj`) work with empty children

- documents/knowledge/elements.yaml
- tests/test_elements.py
- vyxal/elements.py
- vyxal/helpers.py
I couldn't see how to get `wrap` to do exactly what we want, so I made a helper for it. Hope that's okay. Goes towards closing #1119
> Fix behavior of `/` and `Þ÷` when splitting strings/lists

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- vyxal/elements.py
Closes #1150. Matrix Row Reduce is dead, long live Cumul Sums Sans Last Prepend Zero!
> Death to this ÞR (Matrix Row Reduce)

- tests/test_complex.py
- vyxal/elements.py
- vyxal/parse.py
- vyxal/transpile.py
makes the transpiler use the function_stack instead of this
#857 broke this, btw.
> Make vectorised recursion (`vx`) work again

- tests/test_complex.py
- vyxal/LazyList.py
- vyxal/elements.py
It was trying to call the `append` method, which only works for lists.
> Make `gen_from_fn` (`Ḟ`) work with LazyLists

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
> Make `Þİ`  work with swapped args

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
Made `kP` return ASCII characters in the proper order (without a space just as it was) and added `kQ` for all ASCII characters *including* a space.
> Rearrange `kP` and add `kQ`

- documents/knowledge/elements.yaml
- tests/test_elements.py
- vyxal/elements.py
Fixes #1287
Plus:
add more tests for `i`
add more tests for `Ẏ`
add more tests for `Ż`
> Make `i` modular slice strings

- vyxal/elements.py
No linked issue, just a test that doesn't pass.
> Make `Ṁ` insert at negative indices correctly

- .github/workflows/linter.yaml
- vyxal/elements.py
- vyxal/helpers.py
Lifted iterablification of nonlocal variables up in `multiset_intersection` and a few other places. Added a `nonlocal rhs` to the `gen` function inside `multiset_intersection` because `rhs` has to be mutated inside it.
Also modified the linter workflow to exclude `build`, `dist`, and `.git`
> Fix linting issues with nonlocals

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_elements.py
- vyxal/elements.py
The `str` overload is strip white space from both sides just like `øS`, and the `num` overload checks if a number is positive.
> Add overloads for vectorising sum

- vyxal/elements.py
When they're both lazylists, it doesn't matter :p
Fixes #1378
> Fix prepend with lazylists

- tests/test_complex.py
- vyxal/transpile.py
> Make pure complex numbers work again

- vyxal/elements.py
Something like `λ₂[½|T›}↔1ḟ` now works for collatz sequence length.
> Make ḟ work properly with long/unknowably infinite lists

- tests/test_complex.py
- tests/test_parser.py
- vyxal/parse.py
> Add `)` as lambda to newline, and make only `}` close all structures

- vyxal/helpers.py
Under a very restricted system though
- Unicode is normalized as python normalizes it to avoid anything funky there
- No \"'{}_ or backtick in expressions
- No decimals with letters on either side
- No runs of characters longer than 1
- Some remaining characters are converted to helpful sympy functions
Closes #867
> Put sympy back on the menu

- tests/test_complex.py
- vyxal/elements.py
It previously returned `0`, which isn't helpful, given that the first truthy item may also be at index `0`.
> Make Ǒ return -1 if not found

- .github/workflows/test-build.yaml
- .gitpod.Dockerfile
- .gitpod.yml
- shared/src/main/scala/AST.scala
- shared/src/main/scala/Context.scala
- shared/src/main/scala/Elements.scala
- shared/src/main/scala/FuncHelpers.scala
- shared/src/main/scala/Interpreter.scala
- shared/src/main/scala/ListHelpers.scala
- shared/src/main/scala/MiscHelpers.scala
- shared/src/main/scala/Parser.scala
- shared/src/main/scala/StringHelpers.scala
- shared/src/main/scala/VAny.scala
- shared/src/main/scala/VList.scala
- shared/src/test/scala/ElementTests.scala
- shared/src/test/scala/ParserTests.scala
Sorry, this PR is a bunch of unrelated changes:
- Made the code a little more idiomatic in places
- Fix parser tests with trailing nilad moving to front, add simple tests for specific cases of reduce and mold
- Vectorise the add and multiply helpers themselves instead of the element in `Impls`
- Allow setting context vars in `Interpreter.executeFn`, use that for executing `VFun`s
- Get the test-build Github Actions workflow to run on pushes to all branches instead of just version-3
> Assorted changes

- .scalafmt.conf
- jvm/src/main/scala/Main.scala
- jvm/src/main/scala/Repl.scala
- shared/src/main/scala/AST.scala
- shared/src/main/scala/Context.scala
- shared/src/main/scala/Elements.scala
- shared/src/main/scala/FuncHelpers.scala
- shared/src/main/scala/Functions.scala
- shared/src/main/scala/Globals.scala
- shared/src/main/scala/Interpreter.scala
- shared/src/main/scala/Lexer.scala
- shared/src/main/scala/ListHelpers.scala
- shared/src/main/scala/MiscHelpers.scala
- shared/src/main/scala/Modifiers.scala
- shared/src/main/scala/NumberHelpers.scala
- shared/src/main/scala/Parser.scala
- shared/src/main/scala/StringHelpers.scala
- shared/src/main/scala/VAny.scala
- shared/src/main/scala/VList.scala
- shared/src/main/scala/VNum.scala
- shared/src/test/scala/InterpreterTests.scala
Add some Scalafmt rules to automatically rewrite to the new syntax and also group imports. Since it ended up making a *lot* of changes, I made a PR instead of committing directly. The PR should probably be directed towards a different branch but this is more convenient and less likely to cause problems later. One thing that needs some discussion is how many lines are needed before the `end` marker should be inserted. I went with 15 for now but we could make that smaller or bigger depending on what y'all want.
> Modify Scalafmt to rewrite to new syntax

- .github/workflows/deploy-pages.yaml
- build.sbt
This PR is for v3, not v2. It'll deploy Scaladocs to `vyxal.github.io/Vyxal/docs` (shouldn't mess with the interpreter because the interpreter will be at `vyxal.github.io/Vyxal`). It's not actually needed because Vyxal's an application, not a library, but it might help people new to v3. I'll admit that I'm mainly doing this because it'd be kinda cool.
<s>I think GitHub Pages needs to enabled first, though.</s> Thanks lyxal
> Deploy Scaladocs to GitHub Pages

- vyxal/elements.py
Something like `5°2 2 e` would otherwise error
> Improve printing of complex numbers

- documentation/elements.txt
- shared/src/main/scala/Context.scala
- shared/src/main/scala/Elements.scala
- shared/src/main/scala/Lexer.scala
- shared/src/test/scala/ElementTests.scala
- shared/src/test/scala/InterpreterTests.scala
- shared/src/test/scala/ParserTests.scala
Implement the `Ė` element (there wasn't really anything to "implement", just needed to add an element that called all the methods already implemented). Added a few tests for `Ė`.
> Implement execute (`Ė`)

- .scalafmt.conf
- shared/src/main/scala/Context.scala
- shared/src/main/scala/Elements.scala
- shared/src/main/scala/FuncHelpers.scala
- shared/src/main/scala/Functions.scala
- shared/src/main/scala/Globals.scala
- shared/src/main/scala/MiscHelpers.scala
- shared/src/main/scala/Parser.scala
- shared/src/main/scala/StringHelpers.scala
- shared/src/test/scala/ElementTests.scala
This PR was originally just meant to group `addX` and `addXVect` together (hence the branch name) and change their signatures to take the overloads as a single multiline string instead of a list of strings, but I ended up making `Monad`, `Dyad`, `Triad`, `Tetrad` objects extending an `ImplHelpers` class that groups `vectorise`, `fill`, and `toDirectFn` together for each arity. This makes it so a single `addFull` method can be used for all arities, a single `addVect` can be used for all arities, etc. I think this is a better solution, since we can continue making elements almost exactly the same way as before, but there's less code duplication.
I also rewrote the `vectorise` method in `FuncHelpers` (that one operates on function objects/`VFun`s, not `Monad`s, `Dyad`s, etc.). It was the …
> Group arity-specific helpers together

- .github/workflows/lint.yaml
- .scalafix.conf
- build.sbt
- project/plugins.sbt
- shared/src/main/scala/Parser.scala
[Scalafix](https://scalacenter.github.io/scalafix/) is a linting/refactoring tool. It doesn't yet support a lot of rules for Scala 3, but eventually we'll be able to use it to remove unused imports and stuff. I also added a few rules for common mistakes someone new to Scala or the Vyxal codebase might make:
- `CaseBraces` - To warn people that braces aren't needed when they do `case foo => {}`
- `EmptyCheck` - To warn people that `foo.isEmpty` and `foo.nonEmpty` can be used instead of comparing `foo.size`/`foo.length` to 0
- `BooleanToVNum` (Vyxal-specific) - To warn people that explicitly converting booleans to `VNum`s isn't necessary (`if bool then 1 else 0`)
- `MatchingVAny` (Vyxal-specific) - To warn people that it's not necessary to match on `VAny` since all the objects we deal with …
> Add scalafix

- shared/src/main/scala/Context.scala
- shared/src/main/scala/Elements.scala
- shared/src/main/scala/FuncHelpers.scala
- shared/src/test/scala/ElementTests.scala
- shared/src/test/scala/InterpreterTests.scala
Steffan suggested making it variadic so we won't have to do things like `ctx.push(a); ctx.push(b); ctx.push(c)`. Also fixed a minor issue in `Context.makeFnCtx` where if you explicitly gave arguments for a function to use (instead of popping them from the stack), it would give them in the reverse order.
> Make Context#push variadic

- README.md
- tests/test_lexer.py
- vyxal/lexer.py
`#` in `}#` does not get eaten, that's why:
This program prints 1, should print 0:
```
#{}##{
1
```
This program prints 1, should hang:
```
#{}#{ }#
1
```
**Warning**: I did not test this PR because I could not figure out how to run development version.
> fix incorrect behavior of multiline comment

- tests/test_lexer.py
- vyxal/lexer.py
This PR fixes these programs: `#{#` and `#{}`
> Fix `IndexError: deque index out of range` while lexing unclosed multiline comment

- documentation/Interpreter.md
- documentation/README.md
- shared/src/main/scala/Context.scala
- shared/src/main/scala/Interpreter.scala
- shared/src/test/scala/InterpreterTests.scala
This PR makes the parent context of an executing lambda the context that it was originally created in instead of the context it's executing in, so that it has full access to the variables from there. This doesn't work *exactly* like Python, since it's a bit like `nonlocal x` is automatically thrown in whenever you use a variable `x` from the outer context, but I think it's the same as Vyxal v2's behavior.
After discussing with lyxal in chat, context variable N is now last condition value in while loops and context variable M is the while loop's index (they were swapped). I've updated comments and docs a bit, let me know if I put it wrong.
Also added some miscellaneous changes, since we don't have too many people to review PRs and I'm lazy.
> Make scoping work like Python

- shared/src/main/scala/Lexer.scala
- shared/src/main/scala/VNum.scala
- shared/src/test/scala/InterpreterTests.scala
- shared/src/test/scala/LexerTests.scala
Before decimals just didn't work, because of a call to `.toInt`.
Now, all sorts of hanging literals are handled.
> Make decimals and complex literals work better

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
Pointed out by 97.100.97.109 [in chat](https://chat.stackexchange.com/transcript/message/62873860#62873860). `ṁ`'s num overload isn't documented in elements.yaml (but the docstring does have it).
> Add desc of ṁ for num in yml

- documents/knowledge/elements.md
- documents/knowledge/elements.txt
- documents/knowledge/elements.yaml
- static/parsed_yaml.js
- tests/test_complex.py
- vyxal/elements.py
<s>What the linked issue suggests. Since `ȯ`'s description doesn't say just positive integers, it's been changed to be all integers now to avoid duplicating the functionality of `o`.</s> Other way round now, `o` will be all integers, `ȯ` will be positive integers.
> Make `o` use all integers

- build.sbt
- build.sc
- native/src/main/scala/Main.scala
- native/src/main/scala/Repl.scala
- project/plugins.sbt
- shared/src/main/scala/Interpreter.scala
- shared/src/main/scala/Lexer.scala
This branch is for eventually creating Vyxal executables directly using Scala Native. There's also GraalVM, which we should check out too. Executables made by Scala Native will likely be smaller, since they don't contain all the Java stuff that GraalVM has. Scala Native will also be able to optimize more, since it's aware of the original Scala code, while GraalVM works on bytecode. However, the size and performance difference probably won't be big enough to be noticeable, and GraalVM has been around longer than Scala Native and works on JARs, so we may just want to go with that.
> Scala Native support

- pages/main.js
It was using `/worker.js` before, which tried to get it from vyxal.github.io/worker.js. Caught by [lyxal](https://chat.stackexchange.com/transcript/message/62961275#62961275)+[emanresu](https://chat.stackexchange.com/transcript/message/62961367#62961367)
> Relative path for worker.js

- vyxal/elements.py
yeah, pretty weird, but weird cases like `0λ0;İ` doesn't seem to break it.
fixes #1633
> Fix that keep-while-unique element bug

- vyxal/elements.py
I'm not sure if these are the expected results, but
```
0λ›3%;İ   -> ⟨ 1 | 2 | 0 ⟩
0λ›3∵;İ   -> ⟨ 1 | 2 | 3 ⟩
0λ0n¬ß1;İ -> ⟨ 0 | 1 ⟩
0λ0;İ     -> ⟨ ⟩
```
> Fix my fix

- shared/src/main/scala/StringHelpers.scala
Closes #1659 
The problem was Jelly being all weird again.
> Replace `¦` with newlines when decompressing strings

- vyxal/elements.py
Before it was returning `ord(c) - 64` which is not what we need.
See [this program](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDuEEiLCIiLCJ7fH0iXQ==). It is giving `[27, 28, 29]`. With this change, it will give `[0, 0, 0]`, as they are all non-alphabets.
> Make `øA` return 0 for non-alphabets

- vyxal/elements.py
[Before it was returning `1N`](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDuMSLIiwiIiwiLTEiXQ==), but there's a constant for `-1`.
> Make `øċ` return `u` for `-1`

- vyxal/elements.py
Main diagonal (`Þ/`) doesn't error, but anti-diagonal errors ([Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnlxcIiwiIiwiW10iXQ==)).
> Make anti-diagonal (Þ\) not error for an empty list

- vyxal/elements.py
Before [it was just returning an empty string](https://vyxal.pythonanywhere.com/?v=1#WyIiLCIiLCLDuOG5mCIsIiIsIi0xMjMiXQ==) for negative numbers and [giving 0](https://vyxal.pythonanywhere.com/?v=1#WyIiLCIiLCLDuOG5mCIsIiIsIlwiLUNYWElJSVwiIl0=) for negative numerals.
> Make `øR` work for negative numbers

- vyxal/elements.py
Basically there were a few places where `max` was being called with something which could have been an empty list (which would give an error).
Yes, I did test all of them on the online interpreter, and they were all erroring if you gave them empty lists. No, I'm not giving you all the links. No, I don't have time to do the same with `min` right now.
> Fix up a few calls to `max` with an empty list

- vyxal/elements.py
> Make `Ḣ` return an empty string when given an empty string

- documentation/Tests.md
it was pointing to an old folder before, but we're using mill's project structure now
> correct path to tests.yaml in docs

- shared/src/vyxal/Elements.scala
@nayakrujul suggested that `addElem` take a `vectorises` argument like `addFull` for convenience. This PR merges `addElem` and `addVect` into a single `addPart` helper that takes a `vectorises` argument. This'll make `Elements.scala` longer, but it's one less helper to remember. There's like a billion changes in this PR, so enjoy reviewing!
> refactor: Merge addElem and addVect

- shared/src/vyxal/Elements.scala
- shared/test/src/vyxal/ElementTests.scala
Currently, the sublists element won't enumerate every sublist even given unlimited time, so this PR uses `mergeInfLists` to make sure every sublist is enumerated eventually (like cartesian product). Unlike cartesian product, I don't think people usually rely on the exact order of the sublists, so I think this change is probably fine?
> Diagonalize sublists

- vyxal/main.py
1.
You can now specify what type inputs should be treated as. For example
```
!(\d+) (\d+) => (\d+) !=> sss
```
Means that the two inputs are treated as strings, and that the output is considered a string.
The `!=>` is an optional addition that indicates that there's a type string.
```
n => number
s => string
l => list
f => function
```
2.
You can now compare against lists properly.
- [The brackets are formatted correctly](https://vyxal.pythonanywhere.com/?v=2#WyJ+IiwiIiwiKyIsIiIsIlsyLCA0XSwgMiA9PiBbNCwgNl0iXQ==)
> Greatly improve the workings of the `~` flag

- static/main.js
Couldn't do this if it wasn't in scala.js :p
> Add bitstring to answer templates

- tests/test_complex.py
- vyxal/elements.py
> Make it so that `Ǔ` and `ǔ` are considered monadic to modifiers.

- .gitignore
- build.sbt
- build.sc
- js/src/vyxal/JSVyxal.scala
- pages/index.html
- pages/main.js
- pages/os.module.js
- pages/worker.js
To be able to use the Scopt help text, we need module support. Unfortunately, modules are a huge pain to get working. This currently doesn't work. It looks like the line in the web worker where it imports `vyxal.js` makes it so that the web worker doesn't respond? If I replace `"./vyxal.js"` with `"./os.module.js"`, then it does at least print an error message.
> Make Scala.js emit module instead of script
